/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haswalk_jlapack_JLapack */

#ifndef _Included_com_haswalk_jlapack_JLapack
#define _Included_com_haswalk_jlapack_JLapack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haswalk_jlapack_JLapack
 * Method:    dsyev
 * Signature: (ICCI[DI[D)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jlapack_JLapack_dsyev
  (JNIEnv *, jclass, jint, jchar, jchar, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     com_haswalk_jlapack_JLapack
 * Method:    dsysv
 * Signature: (ICII[DI[I[DI)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jlapack_JLapack_dsysv
  (JNIEnv *, jclass, jint, jchar, jint, jint, jdoubleArray, jint, jintArray, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jlapack_JLapack
 * Method:    dposv
 * Signature: (ICII[DI[DI)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jlapack_JLapack_dposv
  (JNIEnv *, jclass, jint, jchar, jint, jint, jdoubleArray, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
